name: Deploy docker-compose to GCE

on:
  push:
    branches: [ master ]

jobs:
  deploy-gce:
    name: deploy docker-compose to gce
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSHKEY }}
      SSH_KEY_PUB: ${{ secrets.SSHKEYPUB }}
      PORT: ${{ secrets.PORT }}
      SSH_PORT: ${{ secrets.SSHPORT }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      GIT_REPOSITORY: https://github.com/dionomusuko/go-docker-template
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir ~/.ssh
          echo ${SSH_KEY} | base64 -d > ~/.ssh/my-ssh-key
          echo ${SSH_KEY_PUB} | base64 -d > ~/.ssh/my-ssh-key.pub
          chmod 600 ~/.ssh/my-ssh-key
      - name: Deploy api serverg
        run: |
          ssh -oStrictHostKeyChecking=no -p ${PORT} ${SSH_USERNAME}@${SSH_PORT} -i ~/.ssh/my-ssh-key
